Repository micrometer-metrics/context-propagation, pull requests merged in 2023-07, with the labels that each got.

#124 Upgrade to Gradle Wrapper 8.2
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: build, type: task

#123 Test utilities and scenarios for working with scopes
  context-propagation/src/test/java/io/micrometer/context/DefaultContextSnapshotDepreactionTests.java
  context-propagation/src/test/java/io/micrometer/context/DefaultContextSnapshotTests.java
  context-propagation/src/test/java/io/micrometer/context/ScopedValueSnapshotTests.java
  context-propagation/src/test/java/io/micrometer/context/observation/NullObservation.java
  context-propagation/src/test/java/io/micrometer/context/observation/Observation.java
  context-propagation/src/test/java/io/micrometer/context/observation/ObservationThreadLocalAccessor.java
  context-propagation/src/test/java/io/micrometer/context/observation/RevertingScope.java
  context-propagation/src/test/java/io/micrometer/context/observation/Scope.java
  context-propagation/src/test/java/io/micrometer/scopedvalue/Scope.java
  context-propagation/src/test/java/io/micrometer/scopedvalue/ScopeHolder.java
  context-propagation/src/test/java/io/micrometer/scopedvalue/ScopedValue.java
  context-propagation/src/test/java/io/micrometer/scopedvalue/ScopedValueTest.java
  context-propagation/src/test/java/io/micrometer/scopedvalue/ScopedValueThreadLocalAccessor.java
Labels: enhancement

#126 Replace sleep with CountDownLatch in tests
  context-propagation/src/test/java/io/micrometer/context/ContextWrappingTests.java
Labels: polish

#131 Reverse order of ThreadLocalAccessors upon scope close
  context-propagation/src/main/java/io/micrometer/context/DefaultContextSnapshot.java
  context-propagation/src/test/java/io/micrometer/context/ScopedValueSnapshotTests.java
  context-propagation/src/test/java/io/micrometer/scopedvalue/ScopedValueThreadLocalAccessor.java
Labels: enhancement
