Repository micrometer-metrics/context-propagation, pull requests merged in 2023-02, with the labels that each got.

#67 Clearing ThreadLocals not present in source context
  context-propagation/src/main/java/io/micrometer/context/ContextSnapshot.java
  context-propagation/src/main/java/io/micrometer/context/DefaultContextSnapshot.java
  context-propagation/src/test/java/io/micrometer/context/DefaultContextSnapshotTests.java
Labels: bug

#69 Add Javadoc since for ThreadLocalAccessor.restore()
  context-propagation/src/main/java/io/micrometer/context/ThreadLocalAccessor.java
Labels: documentation

#74 Revert clearing thread locals not present in source context
  context-propagation/src/main/java/io/micrometer/context/ContextSnapshot.java
  context-propagation/src/main/java/io/micrometer/context/DefaultContextSnapshot.java
  context-propagation/src/test/java/io/micrometer/context/DefaultContextSnapshotTests.java
Labels: type: task
